git clone https://github.com/ros/actionlib.git -b 1.14.0
git clone https://github.com/ros/angles.git -b 1.9.13
git clone https://github.com/ros/bond_core.git -b 1.8.6
git clone https://github.com/ros/catkin.git -b 0.8.10
git clone https://github.com/ros/class_loader.git -b 0.5.0
git clone https://github.com/ros/cmake_modules.git -b 0.5.0
git clone https://github.com/ros/common_msgs.git -b 1.13.1
git clone https://github.com/ros/common_tutorials.git -b 0.2.0
git clone https://github.com/ros-controls/control_msgs.git -b 1.5.2
git clone https://github.com/ros/diagnostics.git -b 1.11.0
git clone https://github.com/ros/dynamic_reconfigure.git -b 1.7.3

git clone https://github.com/ros/executive_smach.git -b 2.5.2
git clone https://github.com/ros/filters.git -b 1.9.2
git clone https://github.com/ros/gencpp.git -b 0.7.0
git clone https://github.com/jsk-ros-pkg/geneus.git -b 3.0.0
git clone https://github.com/ros/genlisp.git -b 0.4.18
git clone https://github.com/ros/genmsg.git -b 0.6.0
git clone https://github.com/sloretz/gennodejs.git -b 2.0.2
git clone https://github.com/ros/genpy.git -b 0.6.15
git clone https://github.com/ros/geometry.git -b 1.13.2
git clone https://github.com/ros/geometry2.git -b 0.7.7
git clone https://github.com/ros/geometry_tutorials.git -b 0.2.3
git clone https://github.com/ros-visualization/gl_dependency.git -b 1.1.2

git clone https://github.com/ros-perception/image_common.git -b 1.12.0
git clone https://github.com/ros-visualization/interactive_markers.git -b 1.12.0
git clone https://github.com/ros/joint_state_publisher.git -b 1.15.1
git clone https://github.com/ros/kdl_parser.git -b 1.14.2
git clone https://github.com/ros-perception/laser_geometry.git -b 1.6.7
git clone https://github.com/ros/media_export.git -b 0.3.0
git clone https://github.com/ros/message_generation.git -b 0.4.1
git clone https://github.com/ros/message_runtime.git -b 0.4.13
git clone https://github.com/ros/metapackages.git -b 1.5.0

git clone https://github.com/ros-planning/navigation_msgs.git -b 1.14.1
git clone https://github.com/ros/nodelet_core.git -b 1.11.0
git clone https://github.com/ros/pluginlib.git -b 1.13.0
git clone https://github.com/ros-visualization/python_qt_binding.git -b 0.4.4
git clone https://github.com/ros-visualization/qt_gui_core.git -b 0.4.2
git clone https://github.com/ros-visualization/qwt_dependency.git -b 1.1.1

git clone https://github.com/ros/resource_retriever.git -b 1.12.7
git clone https://github.com/ros/robot_state_publisher.git -b 1.15.2
git clone https://github.com/ros/ros.git -b 1.15.8
git clone https://github.com/ros/ros_comm.git -b 1.16.0
git clone https://github.com/ros/ros_comm_msgs.git -b 1.11.3
git clone https://github.com/ros/ros_environment.git -b 1.3.2
git clone https://github.com/ros/ros_tutorials.git -b 0.10.2
git clone https://github.com/ros/rosbag_migration_rule.git -b 1.0.1
git clone https://github.com/lucasw/rosconsole.git -b ubuntu_2210
git clone https://github.com/ros/rosconsole_bridge.git -b 0.5.4
git clone https://github.com/ros/roscpp_core.git -b 0.7.3
git clone https://github.com/ros/roslint.git -b 0.12.0
git clone https://github.com/ros/roslisp.git -b 1.9.25
git clone https://github.com/ros/rospack.git -b 2.6.2

git clone https://github.com/ros-visualization/rqt.git -b 0.5.3
git clone https://github.com/ros-visualization/rqt_action.git -b 0.4.9
git clone https://github.com/ros-visualization/rqt_bag.git -b 0.5.1
git clone https://github.com/ros-visualization/rqt_common_plugins.git -b 0.4.9
git clone https://github.com/ros-visualization/rqt_console.git -b 0.4.12
git clone https://github.com/ros-visualization/rqt_dep.git -b 0.4.12
git clone https://github.com/ros-visualization/rqt_graph.git -b 0.4.14
git clone https://github.com/ros-visualization/rqt_image_view.git -b 0.4.17
git clone https://github.com/ros-visualization/rqt_launch.git -b 0.4.9
git clone https://github.com/ros-visualization/rqt_logger_level.git -b 0.4.12
git clone https://github.com/ros-visualization/rqt_moveit.git -b 0.5.11
git clone https://github.com/ros-visualization/rqt_msg.git -b 0.4.10

git clone https://github.com/ros-visualization/rqt_nav_view.git -b 0.5.7
git clone https://github.com/ros-visualization/rqt_plot.git -b 0.4.13
git clone https://github.com/ros-visualization/rqt_pose_view.git -b 0.5.11
git clone https://github.com/ros-visualization/rqt_publisher.git -b 0.4.10
git clone https://github.com/ros-visualization/rqt_py_console.git -b 0.4.10
git clone https://github.com/ros-visualization/rqt_reconfigure.git -b 0.5.5
git clone https://github.com/ros-visualization/rqt_robot_dashboard.git -b 0.5.8
git clone https://github.com/ros-visualization/rqt_robot_monitor.git -b 0.5.15
git clone https://github.com/ros-visualization/rqt_robot_plugins.git -b 0.5.8
git clone https://github.com/ros-visualization/rqt_robot_steering.git -b 0.5.12
git clone https://github.com/ros-visualization/rqt_runtime_monitor.git -b 0.5.10

git clone https://github.com/ros-visualization/rqt_rviz.git -b 0.7.0
git clone https://github.com/ros-visualization/rqt_service_caller.git -b 0.4.10
git clone https://github.com/ros-visualization/rqt_shell.git -b 0.4.11
git clone https://github.com/ros-visualization/rqt_srv.git -b 0.4.9
git clone https://github.com/ros-visualization/rqt_tf_tree.git -b 0.6.4
git clone https://github.com/ros-visualization/rqt_top.git -b 0.4.10
git clone https://github.com/ros-visualization/rqt_topic.git -b 0.4.13
git clone https://github.com/ros-visualization/rqt_web.git -b 0.4.10
git clone https://github.com/ros-visualization/rviz.git -b 1.14.20

git clone https://github.com/ros/std_msgs.git -b 0.5.13
git clone https://github.com/ros/urdf.git -b 1.13.2
git clone https://github.com/ros/urdf_tutorial.git -b 0.5.0
git clone https://github.com/ros-perception/vision_opencv.git -b 1.16.2
git clone https://github.com/ros-visualization/visualization_tutorials.git -b 0.11.0
git clone https://github.com/ros-visualization/webkit_dependency.git -b 1.1.2
git clone https://github.com/ros/xacro.git -b 1.14.17
