sudo apt install libboost-all-dev libconsole-bridge-dev libpoco-dev libtinyxml-dev libtinyxml2-dev libbz2-dev liblz4-dev liblog4cxx-dev libgpgme-dev libgtest-dev uuid-dev \
sip-dev \
qtbase5-dev \
pyqt5-dev \
pyqt5-dev-tools \
libcurl4-openssl-dev \
libeigen3-dev \
liborocos-kdl-dev \
libtf2-bullet-dev \
liburdfdom-headers-dev \
liburdfdom-tools \
liburdfdom-dev \
libyaml-cpp-dev \
libopencv-dev \
libassimp-dev \
libogre-1.9-dev \
ogre-1.9-tools \
python3-nose \
python3-pycryptodome \
python3-defusedxml \
python3-mock \
python3-netifaces \
python3-gnupg \
python3-numpy \
python3-psutil \
python3-catkin-pkg \
python3-rospkg \
python3-pip \
python3-setuptools \
python3-empy \
